name: Deploy to Firebase Rules on Merge
'on':
  push:
    branches:
      - master
jobs:
  linting:
    name: Check for linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run check:style
  emulator_test:
    needs: [linting]
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Run all the tests
        run: npm run build && firebase emulators:exec --project sponsorr-dev --token '$FIREBASE_TOKEN_DEV' 'npm test'
        env:
          FIREBASE_TOKEN_DEV: ${{ secrets.FIREBASE_TOKEN_DEV }}
  build_and_deploy:
    needs: [emulator_test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install npm packages
        run: npm ci
      - name: Deploy to Firebase
        run: firebase deploy --only functions,firestore:rules --project sponsorr-prod --token '$FIREBASE_TOKEN_PROD' -f --non-interactive
        env:
          FIREBASE_TOKEN_PROD: ${{ secrets.FIREBASE_TOKEN_PROD }}
